@extends ('layouts.main-layout')
@section('page-title', 'Nutricionista')
@section('content-area')
    @include('components.inicio.hero')
    @include('components.inicio.servicios')
    @include('components.inicio.frase')
    @include('components.inicio.testimonios')
    @include('components.inicio.sobreMi')
    @include('components.inicio.precios')
@endsection
